project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
    - "!templates/"
    - "!posts/templates/"



website:
  page-navigation: true
  title: "Embracing complexity"
  site-url: "https://danielborek.me"
  page-footer:
      left: "Blog made with 💜 and [Quarto](https://quarto.org/), by Daniel Borek. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
      right:
        - icon: github
          href: https://github.com/danieltomasz/
        - icon: twitter
          href: https://twitter.com/danieltomasz
        - icon: envelope
          href: mailto:daniel.borek@ugent.be
  navbar:
    left:
      -  text: "Daniel Borek"
    right:
      - text: "posts"
        file: index.qmd
      - text: "about"
        file: posts/about.qmd

format:
  html:
    highlight-style: a11y
    theme: styles.scss
    toc: true
    toc-depth: 3
    toc-location: left

comments:
  giscus:
    repo: danieltomasz/danieltomasz.github.io

resources:
  - CNAME