baseURL = "https://danieltomasz.github.io"
languageCode = "en-us"
title = "Daniel Borek"
theme = "succulent"


[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 10


  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog"
    weight = 20

[[menu.main]]
name = "tags"
url = "/tags"
weight = 30

[[menu.main]]
name = "about"
url = "/about"
weight = 40


[outputs]
  home = [ "RSS", "HTML"]
  section  = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"

[markup]
  [markup.highlight]
    style = "github"

    
[params]
mainSectionTitle = "blog"
  colortheme = "classic" # dark, light, white, or classic
    description = "Hi there! 👋 I’m Daniel, a productivity nerd, open science and linux enthusiast and a PhD candidate working to learn more about the nature of neural oscillations."

[[params.social]]
  name = "github"
  link = "https://github.com/danieltomasz"
[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/daniel-borek-209003a6/"
  [[params.social]]
  name = "twitter"
  link = "https://www.twitter.com/danieltomasz"


