baseURL = "https://danielborek.me"
languageCode = "en-us"
title = "Daniel Borek"
theme = 'lines'

[Author]
  name = "Daniel Borek"

[params]
  description = "A personal musings and learning by Daniel Borek"
  author = "Daniel Borek"
  copyright = ""
  logo = ""
  orgName = "Daniel Borek"
  orgLocal = ""
  disableComments = false

[params.giscus]
 repo="danieltomasz/danieltomasz.github.io"
 repo-id="MDEwOlJlcG9zaXRvcnkzMzM0MDUzMzY="
 category="Comments"
 category-id="DIC_kwDOE99cmM4CVDXo"
 mapping="title"
 strict="0"
 reactions-enabled="1"
 emit-metadata="1"
 input-position="bottom"
 theme="light"
 lang="en"
 loading="lazy"
 crossorigin="anonymous"
 reactionsEnabled = "1"

[params.assets]
    favicon = "img/favicon.ico"

enableGitInfo = true
enableEmoji = true

[frontmatter]
#  date  = [":filename", ":default", "lastmod"]
  author = "Daniel Borek"
  github = "danieltomasz"
  facebook = ""
  og_image = ""
  sitename = ""
  twitter = "danieltomasz"
  date = ["date", "publishDate", "lastmod"]
  lastmod = [  "lastmod", ":git", "date", ]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]
#disableKinds = ["section", "categories"]


disqusShortname = ""
pygmentsStyle = "pygments"
pygmentsCodefences = true
pygmentsuseclasses = false



#pygmentsUseClasses = true
paginate = 999
minify = true

ignoreFiles = [ "\\.qmd$", "\\.ipynb$", "\\.py$" ]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    # one of: https://xyproto.github.io/splash/docs/ 
    style = "github"
    linenos = false
    lineNumbersInTable = false
    linenostart = false
    noClasses = true

[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true



[permalinks]
#  posts = "/:year/:month/:day/:filename"
  posts = "/:year/:filename"
  pages = "/:slug"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
    identifier = "index"
    name       = "Index"
    url        = "/"
    weight     = -111

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = -200

  [[menu.main]]
    identifier = "rss"
    name       = "RSS"
    url        = "/atom.xml"
    weight     = -10


[[params.social]]
  name = "github"
  link = "https://github.com/danieltomasz"
[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/daniel-borek-209003a6/"
  [[params.social]]
  name = "twitter"
  link = "https://www.twitter.com/danieltomasz"

