baseURL = "https://danieltomasz.github.io"
languageCode = "en-us"
title = "Daniel Borek"
theme = "simplecss"


[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 10


  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog"
    weight = 20


  [[menu.main]]
    identifier = "til"
    name = "today I learned"
    url = "/til"
    weight = 30

[[menu.main]]
    identifier = "contact"
    name = "contact"
    url = "/contact"
    weight = 40


[outputs]
  home = [ "RSS", "HTML"]
  section  = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"

[markup]
  [markup.highlight]
    style = "monokai"
